name: github-runner CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Forgejo
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.CI_REGISTRY_ADDRESS }}
          username: ${{ vars.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.CI_REGISTRY_ADDRESS }}/${{ vars.CI_REGISTRY_IMAGE }}:1.0.0
